import { makeApi, makeEndpoint, ZodiosEndpointDefinitions } from '@zodios/core';
import { z } from 'zod';

const graphqlResponse = z.object({
  data: z.object({
    publishedDatasources: z.array(
      z.object({
        name: z.string(),
        description: z.string().or(z.null()),
        owner: z.object({
          name: z.string(),
        }),
        fields: z.array(
          z.object({
            name: z.string(),
            isHidden: z.boolean(),
            description: z.string().or(z.null()),
            descriptionInherited: z.array(
              z.object({
                attribute: z.string(),
                value: z.string(),
              }),
            ),
            fullyQualifiedName: z.string(),
            __typename: z.string(),
            // Common field properties (optional since they depend on field type)
            dataCategory: z.string().optional(),
            role: z.string().optional(),
            dataType: z.string().optional(),
            defaultFormat: z.string().or(z.null()).optional(),
            semanticRole: z.string().or(z.null()).optional(),
            aggregation: z.string().or(z.null()).optional(),
            aggregationParam: z.string().or(z.null()).optional(),
            // CalculatedField specific properties
            formula: z.string().optional(),
            isAutoGenerated: z.boolean().optional(),
            hasUserReference: z.boolean().optional(),
            // BinField specific properties
            binSize: z.number().optional(),
            // GroupField specific properties
            hasOther: z.boolean().optional(),
            // CombinedSetField specific properties
            delimiter: z.string().optional(),
            combinationType: z.string().optional(),
          }),
        ),
      }),
    ),
  }),
});

export type GraphQLResponse = z.infer<typeof graphqlResponse>;

const graphqlEndpoint = makeEndpoint({
  method: 'post',
  path: '/graphql',
  alias: 'graphql',
  response: graphqlResponse,
  parameters: [
    {
      name: 'query',
      type: 'Body',
      schema: z.object({
        query: z.string(),
      }),
    },
  ],
});

const metadataApi = makeApi([graphqlEndpoint]);
export const metadataApis = [...metadataApi] as const satisfies ZodiosEndpointDefinitions;
